apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskflow.componentFullname" (dict "root" . "component" "api-gateway") }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "taskflow.componentLabels" (dict "root" . "component" "api-gateway") | nindent 4 }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  selector:
    {{- include "taskflow.selectorLabels" (dict "root" . "component" "api-gateway") | nindent 4 }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: http
      name: http
