apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: taskflow
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: taskflow
data:
  POSTGRES_DB: "taskflow"
